version: '2.0'
services:
  selogertoken:
    build:
      dockerfile: seloger-token.Dockerfile
      context: .
    container_name: hobo-seloger-token

  crawler:
    build:
      dockerfile: crawler.Dockerfile
      context: .
    container_name: hobo-sapiens-crawler
    environment:
      - HS_TELEGRAM_BOT_TOKEN
      - HS_TELEGRAM_CHAT_ID
      - HS_SELOGER_TOKEN_HOST=selogertoken

#    ports:
#    - "5000:5000"
#    volumes:
#    - .:/code
#    - logvolume01:/var/log
#    links:
#    - redis
#  redis:
#    image: redis
#volumes:
#  logvolume01: {}
